DjangoPractice/urls.py
import DjangoPractice.settings as settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from news import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('news.urls')),
    path('users/', include('users.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = views.page_not_found

admin.site.site_header = 'Панель администрирования'
admin.site.index_title = 'Новостной портал'

news/urls.py
from django.urls import path, re_path, include
from rest_framework import routers

from . import views
from .api import api


router = routers.SimpleRouter()
router.register(r'news', api.NewsViewSet, basename='api')

urlpatterns = [
    path('', views.NewsHome.as_view(), name='home'),
    path('about/', views.about, name='about'),

    path('addpage/', views.AddPage.as_view(), name='add_page'),

    path('post/<slug:post_slug>/', views.ShowPost.as_view(), name='post'),

    path('category/<slug:cat_slug>/', views.NewsCategory.as_view(), name='category'),
    path('tag/<slug:tag_slug>/', views.NewsTags.as_view(), name='tag'),

    path('edit/<int:pk>/', views.UpdatePage.as_view(), name='update_page'),

    path('api/', include(router.urls)),

    path('api/auth/', include('djoser.urls')),
    re_path(r'^auth/', include('djoser.urls.authtoken')),
]

users/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth.views import LogoutView, PasswordChangeView, PasswordChangeDoneView, PasswordResetView, \
    PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from . import views

app_name = "users"

urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.RegisterUser.as_view(), name='register'),
    path('profile/', views.ProfileUser.as_view(), name='profile'),
    path('password-change/', views.UserPasswordChange.as_view(), name='password_change'),
    path('password-change/done/', PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'),
        name='password_change_done'),

    path('password-reset/',
        PasswordResetView.as_view(
        template_name="users/password_reset_form.html",
        email_template_name="users/password_reset_email.html",
        success_url=reverse_lazy("users:password_reset_done")
         ), name='password_reset'),
    path('password-reset/done/',
        PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"), name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view( template_name="users/password_reset_confirm.html",
            success_url=reverse_lazy("users:password_reset_complete")
         ), name='password_reset_confirm'),
    path('password-reset/complete/',
        PasswordResetCompleteView.as_view(template_name="users/password_reset_complete.html"),
        name='password_reset_complete'),

]

templates/base.html
{% load static %}
{% load news_tags %}
<!DOCTYPE html>
<html>
<head>
	<title>{{title}}</title>
	<link type="text/css" href="{% static 'news/css/styles.css' %}" rel="stylesheet" />
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<link rel="shortcut icon" href="{% static 'news/images/icon.png' %}" type="image/x-icon"/>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<table class="table-page" border=0 cellpadding="0" cellspacing="0">
<tr><td valign=top>
{% block mainmenu %}
		<div class="header">
			<ul id="mainmenu" class="mainmenu">
			    <li class="logo"><a href="{% url 'home' %}"><div class="logo"></div></a></li>

                {% for m in mainmenu %}
                    <li><a href="{% url m.url_name %}">{{m.title}}</a></li>
                {% endfor %}
                    {% if user.is_authenticated %}
                        <li class="last"><a href="{% url 'users:profile' %}"> {{ user.username }} </a> | <a href="{% url 'users:logout' %}">Выйти</a></li>
                    {% else %}
                        <li class="last"><a href="{% url 'users:login' %}">Войти</a> | <a href="{% url 'users:register' %}">Регистрация</a></li>
                    {% endif %}

			</ul>
			<div class="clear"></div>
		</div>
{% endblock mainmenu %}


<table class="table-content" border=0 cellpadding="0" cellspacing="0">
<tr>
<!-- Sidebar слева -->
	<td valign="top" class="left-chapters">
	<ul id="leftchapters">
        {% if category_selected == 0 %}
            <li class="selected">Все категории</li>
        {% else %}
            <li><a href="{% url 'home' %}">Все категории</a></li>
        {% endif %}

        {% show_categories category_selected %}

        <li>{% show_all_tags %}</li>
	</ul>
</td>
<!-- Конец Sidebar'а -->
<td valign="top" class="content">
	<!-- Хлебные крошки -->
	{% block breadcrumbs %}
	{% endblock %}

<!-- Блок контента -->
	<div class="content-text">
{% block content %}
{% endblock %}
	</div>
<!-- Конец блока контента -->

{% block navigation %}
{% endblock %}

</td></tr></table>
</td></tr>
<!-- Footer -->
<tr><td valign=top>
	<div id="footer">
		<p style="text-align: center">&copy; 2024</p>
	</div>
</td></tr></table>
<!-- Конец footer'а и страницы -->
</body>
</html>